### ISSUE TITLE
dev roadmap

### ISSUE THREAD

**Issue by just-an-dev** [just-an-dev/sodogetip#91]
- [x] only use confirmed TX
- [x] remove fail over system
- [x] add tip in queue if we have pending
- [x] move pending tip to use publish system
- [x] make TxPublish system
- [ ] add multisig (close #4 )
